add --jwts-filename flag to use pre-existing jwts from a specific file
domsolutions/gopayloader pull request #7
Opened 2023-07-03 21:05 UTC by nmaltais

Tests are failing because GET_RSA_JWT throws "jwt_generator: retrieving; corrupt jwt cache, wanted 8 bytes got 0"

I suspect this was happening before but it is only getting caught now because of this piece added in payloader.handleReqs()

![image](https://github.com/domsolutions/gopayloader/assets/10351705/2f8429c1-4b01-48e2-a630-b822807627db)

I'm not sure why it's happening though

2023-07-06 13:02 UTC, domsolutions requested changes

2023-07-06 13:02 UTC, domsolutions commented on pkgs/jwt-generator/jwt.go
> +	JwtsFilename        string
NIT spacing

2023-07-06 13:02 UTC, domsolutions commented on cmd/payloader/run.go
> +	argJWTsFilename    = "jwts-filename"
spacing

2023-07-10 14:45 UTC, nmaltais commented on README.md
> +  -f, --jwts-filename string     File name in .cache where the JWTs to use are stored
Thanks! Had forgotten to edit the README

2023-07-10 14:45 UTC, nmaltais commented on pkgs/jwt-generator/jwt.go
> +		jwtRegex, _ := regexp.Compile(`[\w-]{2,}\.[\w-]{2,}\.[\w-]{2,}`)
True, and the sample file in /test should be enough to show a valid file format

2023-08-21 13:45 UTC, merged